/**
 * Compile per-agent config files from a `.agents/agents/` source tree.
 *
 * Source layout (since the condash.md/conception.md split):
 *   - `.agents/agents/condash.md`     — condash-shipped head: H1 + `## General`
 *   - `.agents/agents/conception.md`  — user-owned tail: `## Specifics` …
 *   - `.agents/agents/claude.md`      — Claude-only fragment
 *   - `.agents/agents/kimi.md`        — Kimi-only fragment
 *   - `.agents/agents/opencode.md`    — OpenCode-only fragment
 *
 * `condash.md` + `conception.md` concatenated reproduce the legacy single-file
 * `common.md` (head before `## Specifics`, then the Specifics tail), so the
 * orchestrator (`compileAgentConfigs` in `files.ts`) joins them via
 * `combineAgentSource` and feeds the result to the unchanged `compileAgentConfig`:
 * the agent fragment is spliced in just before the `## Specifics` heading and
 * `{{ var }}` substitution runs over the merge. A legacy tree that still has
 * only `common.md` is handled by `splitLegacyCommon` (read + migrate).
 */

import { type HarnessId, HARNESS_IDS, HARNESSES } from '../shared/harnesses';

/** An AGENTS.md target is exactly a harness — sourced from the unified registry
 *  (`src/shared/harnesses.ts`). */
export type AgentsMdTarget = HarnessId;

export const AGENTS_MD_TARGETS: readonly AgentsMdTarget[] = HARNESS_IDS;

/**
 * Output path per target, relative to the conception root.
 *
 * OpenCode's config lands inside its own `.opencode/` dir — **never** the
 * conception-root `AGENTS.md`, which condash manages via the shipped-files
 * migration (see `src/cli/commands/files.ts`). OpenCode does not
 * auto-discover `.opencode/AGENTS.md`, so `condash skills install` writes (or
 * merges) the pointer into the conception-root `opencode.json`
 * (`instructions: [".opencode/AGENTS.md"]`) — see `ensureOpencodeConfig` in
 * `src/cli/commands/files.ts`. User scope instead writes
 * `~/.config/opencode/AGENTS.md`, which OpenCode reads natively as global
 * config (`userAgentConfigOutput`).
 */
export const AGENTS_MD_OUTPUTS: Record<AgentsMdTarget, string> = {
  claude: HARNESSES.claude.agentsMdOutput,
  kimi: HARNESSES.kimi.agentsMdOutput,
  opencode: HARNESSES.opencode.agentsMdOutput,
};

/** Default variable map per target, applied via `{{ var }}` substitution. */
export function defaultVariables(target: AgentsMdTarget): Record<string, string> {
  switch (target) {
    case 'claude':
      return {
        agent_name: 'Claude',
        skills_dir: '.claude/skills/',
        agent_config: 'CLAUDE.md',
        memory_dir: '~/.claude/projects/<encoded-path>/memory/',
      };
    case 'kimi':
      return {
        agent_name: 'Kimi',
        skills_dir: '.kimi/skills/',
        agent_config: 'AGENTS.md',
        // No native memory in Kimi — substitute empty.
        memory_dir: '',
      };
    case 'opencode':
      return {
        agent_name: 'OpenCode',
        skills_dir: '.opencode/skills/',
        agent_config: '.opencode/AGENTS.md',
        // No native curated memory in OpenCode — substitute empty.
        memory_dir: '',
      };
  }
}

export interface CompileAgentConfigOptions {
  /** Override / extend the default variable map for this target. */
  variables?: Record<string, string>;
  /**
   * Short description of the source location, embedded in the generated-by
   * header at the top of the compiled output (e.g. `.agents/agents/` for
   * conception scope, `~/.config/agents/agents/` for user scope). Defaults
   * to `.agents/agents/` when omitted.
   */
  sourceDescription?: string;
}

/**
 * Merge `common.md` with the per-agent fragment, substitute variables, and
 * prepend a generated-by header so direct edits to the compiled file surface
 * the regenerate-on-install behavior.
 *
 * The agent fragment is spliced in just before the first `## Specifics`
 * heading in common.md. If common.md lacks that heading, the fragment is
 * appended. If the agent file is empty or missing, common.md is returned
 * unchanged (after variable substitution).
 */
export function compileAgentConfig(
  common: string,
  agentFragment: string,
  target: AgentsMdTarget,
  opts: CompileAgentConfigOptions = {},
): string {
  const variables = { ...defaultVariables(target), ...(opts.variables ?? {}) };
  let merged: string;

  if (!agentFragment.trim()) {
    merged = common;
  } else {
    merged = spliceBeforeSpecifics(common, agentFragment);
  }

  const source = opts.sourceDescription ?? '.agents/agents/';
  const header = `<!-- Generated by \`condash skills install\` from ${source} — edits will be lost on next install. -->\n\n`;
  return header + substituteVariables(merged, variables);
}

/**
 * Find the first `## Specifics` heading in `common` and insert `fragment`
 * immediately before it, separated by a single blank line.
 */
function spliceBeforeSpecifics(common: string, fragment: string): string {
  const lines = common.split('\n');
  let insertIndex = -1;
  for (let i = 0; i < lines.length; i++) {
    if (/^##\s+Specifics\s*$/.test(lines[i])) {
      insertIndex = i;
      break;
    }
  }

  const trimmedFragment = fragment.trimEnd();
  if (insertIndex === -1) {
    // No ## Specifics — append with a blank line separator.
    const sep = common.endsWith('\n') ? '' : '\n';
    return common + sep + '\n' + trimmedFragment + '\n';
  }

  const before = lines.slice(0, insertIndex);
  const after = lines.slice(insertIndex);
  // Ensure a blank line between the preceding content and the fragment.
  const result = [...before];
  if (result.length > 0 && result[result.length - 1] !== '') {
    result.push('');
  }
  result.push(trimmedFragment);
  result.push('');
  result.push(...after);
  return result.join('\n') + '\n';
}

/**
 * Join the condash-shipped head (`condash.md`) and the user-owned tail
 * (`conception.md`) into the single document the compiler consumes. The result
 * reproduces the legacy `common.md`: the head (ending with the `## General`
 * body) followed by the tail (starting at `## Specifics`). Either side may be
 * empty — an empty tail yields the head alone, an empty head yields the tail.
 */
export function combineAgentSource(condashHead: string, conceptionTail: string): string {
  const head = condashHead.replace(/\s+$/, '');
  const tail = conceptionTail.replace(/^\s+/, '').replace(/\s+$/, '');
  if (!head) return tail ? tail + '\n' : '';
  if (!tail) return head + '\n';
  return `${head}\n\n${tail}\n`;
}

/**
 * Split a legacy single-file `common.md` at its first `## Specifics` heading
 * into the condash-shipped head and the user-owned tail. The tail keeps the
 * `## Specifics` heading. When there is no `## Specifics`, the whole document
 * is the head and the tail is empty.
 */
export function splitLegacyCommon(common: string): { head: string; tail: string } {
  const lines = common.split('\n');
  for (let i = 0; i < lines.length; i++) {
    if (/^##\s+Specifics\s*$/.test(lines[i])) {
      const head = lines.slice(0, i).join('\n').replace(/\s+$/, '') + '\n';
      const tailBody = lines.slice(i).join('\n').replace(/\s+$/, '');
      return { head, tail: tailBody + '\n' };
    }
  }
  return { head: common, tail: '' };
}

const VARIABLE_RE = /\{\{\s*([A-Za-z_][A-Za-z0-9_]*)\s*\}\}/g;

function substituteVariables(content: string, variables: Record<string, string>): string {
  return content.replace(VARIABLE_RE, (_, name: string) => {
    const value = variables[name];
    return value === undefined ? '' : value;
  });
}
