/**
 * Compile per-agent config files from a `.agents/agents/` source tree.
 *
 * Source layout:
 *   - `.agents/agents/common.md`      — shared content (must contain `## Specifics`)
 *   - `.agents/agents/claude.md`      — Claude-only fragment
 *   - `.agents/agents/kimi.md`        — Kimi-only fragment
 *   - `.agents/agents/opencode.md`    — OpenCode-only fragment
 *
 * The compile step inserts the agent-specific fragment into `common.md`
 * immediately before the `## Specifics` heading, then applies `{{ var }}`
 * variable substitution from the per-target map.
 */

export type AgentsMdTarget = 'claude' | 'kimi' | 'opencode';

export const AGENTS_MD_TARGETS: readonly AgentsMdTarget[] = ['claude', 'kimi', 'opencode'] as const;

/**
 * Output path per target, relative to the conception root.
 *
 * OpenCode's config lands inside its own `.opencode/` dir — **never** the
 * conception-root `AGENTS.md`, which condash manages via the shipped-files
 * migration (see `src/cli/commands/files.ts`). OpenCode does not
 * auto-discover `.opencode/AGENTS.md`, so a project points to it with an
 * `opencode.json` `instructions` entry (`[".opencode/AGENTS.md"]`) — see the
 * skills-pane guide. User scope instead writes `~/.config/opencode/AGENTS.md`,
 * which OpenCode reads natively as global config (`userAgentConfigOutput`).
 */
export const AGENTS_MD_OUTPUTS: Record<AgentsMdTarget, string> = {
  claude: '.claude/CLAUDE.md',
  kimi: '.kimi/AGENTS.md',
  opencode: '.opencode/AGENTS.md',
};

/** Default variable map per target, applied via `{{ var }}` substitution. */
export function defaultVariables(target: AgentsMdTarget): Record<string, string> {
  switch (target) {
    case 'claude':
      return {
        agent_name: 'Claude',
        skills_dir: '.claude/skills/',
        agent_config: 'CLAUDE.md',
        memory_dir: '~/.claude/projects/<encoded-path>/memory/',
      };
    case 'kimi':
      return {
        agent_name: 'Kimi',
        skills_dir: '.kimi/skills/',
        agent_config: 'AGENTS.md',
        // No native memory in Kimi — substitute empty.
        memory_dir: '',
      };
    case 'opencode':
      return {
        agent_name: 'OpenCode',
        skills_dir: '.opencode/skills/',
        agent_config: '.opencode/AGENTS.md',
        // No native curated memory in OpenCode — substitute empty.
        memory_dir: '',
      };
  }
}

export interface CompileAgentConfigOptions {
  /** Override / extend the default variable map for this target. */
  variables?: Record<string, string>;
  /**
   * Short description of the source location, embedded in the generated-by
   * header at the top of the compiled output (e.g. `.agents/agents/` for
   * conception scope, `~/.config/agents/agents/` for user scope). Defaults
   * to `.agents/agents/` when omitted.
   */
  sourceDescription?: string;
}

/**
 * Merge `common.md` with the per-agent fragment, substitute variables, and
 * prepend a generated-by header so direct edits to the compiled file surface
 * the regenerate-on-install behavior.
 *
 * The agent fragment is spliced in just before the first `## Specifics`
 * heading in common.md. If common.md lacks that heading, the fragment is
 * appended. If the agent file is empty or missing, common.md is returned
 * unchanged (after variable substitution).
 */
export function compileAgentConfig(
  common: string,
  agentFragment: string,
  target: AgentsMdTarget,
  opts: CompileAgentConfigOptions = {},
): string {
  const variables = { ...defaultVariables(target), ...(opts.variables ?? {}) };
  let merged: string;

  if (!agentFragment.trim()) {
    merged = common;
  } else {
    merged = spliceBeforeSpecifics(common, agentFragment);
  }

  const source = opts.sourceDescription ?? '.agents/agents/';
  const header = `<!-- Generated by \`condash skills install\` from ${source} — edits will be lost on next install. -->\n\n`;
  return header + substituteVariables(merged, variables);
}

/**
 * Find the first `## Specifics` heading in `common` and insert `fragment`
 * immediately before it, separated by a single blank line.
 */
function spliceBeforeSpecifics(common: string, fragment: string): string {
  const lines = common.split('\n');
  let insertIndex = -1;
  for (let i = 0; i < lines.length; i++) {
    if (/^##\s+Specifics\s*$/.test(lines[i])) {
      insertIndex = i;
      break;
    }
  }

  const trimmedFragment = fragment.trimEnd();
  if (insertIndex === -1) {
    // No ## Specifics — append with a blank line separator.
    const sep = common.endsWith('\n') ? '' : '\n';
    return common + sep + '\n' + trimmedFragment + '\n';
  }

  const before = lines.slice(0, insertIndex);
  const after = lines.slice(insertIndex);
  // Ensure a blank line between the preceding content and the fragment.
  const result = [...before];
  if (result.length > 0 && result[result.length - 1] !== '') {
    result.push('');
  }
  result.push(trimmedFragment);
  result.push('');
  result.push(...after);
  return result.join('\n') + '\n';
}

const VARIABLE_RE = /\{\{\s*([A-Za-z_][A-Za-z0-9_]*)\s*\}\}/g;

function substituteVariables(content: string, variables: Record<string, string>): string {
  return content.replace(VARIABLE_RE, (_, name: string) => {
    const value = variables[name];
    return value === undefined ? '' : value;
  });
}
