import { describe, expect, it } from 'vitest';
import { compileAgentConfig } from './compile';

/** Strip the generated-by header and the blank line that follows it. */
function body(compiled: string): string {
  const match = compiled.match(/^<!-- Generated by [^>]*-->\n\n/);
  return match ? compiled.slice(match[0].length) : compiled;
}

describe('compileAgentConfig — generated-by header', () => {
  it('prepends a generated-by header naming the default source', () => {
    const out = compileAgentConfig('Hi.', '', 'claude');
    expect(out).toMatch(
      /^<!-- Generated by `condash skills install` from \.agents\/agents\/ — edits will be lost on next install\. -->\n\n/,
    );
  });

  it('honours sourceDescription override in the header', () => {
    const out = compileAgentConfig('Hi.', '', 'kimi', {
      sourceDescription: '~/.config/agents/agents/',
    });
    expect(out).toMatch(
      /^<!-- Generated by `condash skills install` from ~\/\.config\/agents\/agents\/ — /,
    );
  });
});

describe('compileAgentConfig — fragment insertion', () => {
  it('inserts fragment before ## Specifics', () => {
    const common = '# Title\n\n## General\n\nContent.\n\n## Specifics\n\nSpecific content.\n';
    const fragment = '### Claude\n\n- Claude-only rule.\n';
    const out = compileAgentConfig(common, fragment, 'claude');
    expect(out).toContain('## General');
    expect(out).toContain('### Claude');
    expect(out.indexOf('### Claude')).toBeLessThan(out.indexOf('## Specifics'));
    expect(out).toContain('Specific content.');
  });

  it('appends fragment when ## Specifics is missing', () => {
    const common = '# Title\n\n## General\n\nContent.\n';
    const fragment = '### Kimi\n\n- Kimi-only rule.\n';
    const out = compileAgentConfig(common, fragment, 'kimi');
    expect(out).toContain('### Kimi');
    expect(out.indexOf('Content.')).toBeLessThan(out.indexOf('### Kimi'));
  });

  it('returns common unchanged when fragment is empty', () => {
    const common = '# Title\n\n## Specifics\n\nContent.\n';
    const out = compileAgentConfig(common, '', 'claude');
    expect(body(out)).toBe('# Title\n\n## Specifics\n\nContent.\n');
  });

  it('returns common unchanged when fragment is whitespace-only', () => {
    const common = '# Title\n\n## Specifics\n\nContent.\n';
    const out = compileAgentConfig(common, '   \n\n  ', 'kimi');
    expect(body(out)).toBe('# Title\n\n## Specifics\n\nContent.\n');
  });
});

describe('compileAgentConfig — variable substitution', () => {
  it('substitutes {{ skills_dir }} per target', () => {
    const common = 'Skills at {{ skills_dir }}.';
    expect(body(compileAgentConfig(common, '', 'claude'))).toBe('Skills at .claude/skills/.');
    expect(body(compileAgentConfig(common, '', 'kimi'))).toBe('Skills at .kimi/skills/.');
  });

  it('substitutes {{ agent_config }} per target', () => {
    const common = 'Config is {{ agent_config }}.';
    expect(body(compileAgentConfig(common, '', 'claude'))).toBe('Config is CLAUDE.md.');
    expect(body(compileAgentConfig(common, '', 'kimi'))).toBe('Config is AGENTS.md.');
  });

  it('replaces unknown variables with empty string', () => {
    expect(body(compileAgentConfig('Hello {{ unknown }}.', '', 'claude'))).toBe('Hello .');
  });

  it('substitutes {{ memory_dir }} per target', () => {
    const common = 'Memory at {{ memory_dir }}.';
    expect(body(compileAgentConfig(common, '', 'kimi'))).toBe('Memory at .');
    expect(compileAgentConfig(common, '', 'claude')).toContain('~/.claude/projects/');
  });

  it('allows variable overrides', () => {
    const out = compileAgentConfig('{{ skills_dir }}', '', 'claude', {
      variables: { skills_dir: 'custom/' },
    });
    expect(body(out)).toBe('custom/');
  });

  it('substitutes OpenCode variables', () => {
    expect(body(compileAgentConfig('{{ agent_name }}', '', 'opencode'))).toBe('OpenCode');
    expect(body(compileAgentConfig('{{ skills_dir }}', '', 'opencode'))).toBe('.opencode/skills/');
    expect(body(compileAgentConfig('{{ agent_config }}', '', 'opencode'))).toBe(
      '.opencode/AGENTS.md',
    );
    expect(body(compileAgentConfig('{{ memory_dir }}', '', 'opencode'))).toBe('');
  });
});
